services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecos
    ports:
      - "5432:5432"
    volumes:
      - ecos_db_data:/var/lib/postgresql/data

volumes:
  ecos_db_data:

